# Generated by Django 4.1.2 on 2022-10-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="card",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="store_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="store_owner",
        ),
    ]
